/**
 *@Generated by sagacity-quickvo 4.18
 */
package com.sqltoy.dyndatasource.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.dyndatasource.vo.base.AbstractOrderInfoVO;

/**
 * @project sqltoy-dyndatasource
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_order_info,Remark:支付订单表 	
 */
@SqlToyEntity
public class OrderInfoVO extends AbstractOrderInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2373114411777134265L;
	
	/** default constructor */
	public OrderInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public OrderInfoVO(String orderId)
	{
		this.orderId=orderId;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public OrderInfoVO clone() {
		try {
			return (OrderInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
