/**
 *@Generated by sagacity-quickvo 4.15
 */
package com.sqltoy.quickstart.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.time.LocalDate;
import java.sql.Blob;
import java.time.LocalDateTime;
import com.sqltoy.quickstart.vo.base.AbstractStaffInfoVO;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0 Table: sqltoy_staff_info,Remark:员工信息表
 */
@SqlToyEntity
public class StaffInfoVO extends AbstractStaffInfoVO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 8872936239782687517L;

	/** default constructor */
	public StaffInfoVO() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffInfoVO(String staffId) {
		this.staffId = staffId;
	}

	/** minimal constructor */
	public StaffInfoVO(String staffId, String staffCode, String staffName, String organId, String sexType,
			LocalDate entryDate, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime,
			Integer status) {
		this.staffId = staffId;
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.organId = organId;
		this.sexType = sexType;
		this.entryDate = entryDate;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.status = status;
	}

	/** full constructor */
	public StaffInfoVO(String staffId, String staffCode, String staffName, String organId, String sexType,
			LocalDate birthday, LocalDate entryDate, LocalDate termDate, byte[] photo, String country,
			String censusRegister, String address, String email, String telNo, String post, String postGrade,
			String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, Integer status) {
		this.staffId = staffId;
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.organId = organId;
		this.sexType = sexType;
		this.birthday = birthday;
		this.entryDate = entryDate;
		this.termDate = termDate;
		this.photo = photo;
		this.country = country;
		this.censusRegister = censusRegister;
		this.address = address;
		this.email = email;
		this.telNo = telNo;
		this.post = post;
		this.postGrade = postGrade;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.status = status;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	private LocalDate beginDate;

	private LocalDate endDate;

	/**
	 * 机构名称
	 */
	private String organName;

	/**
	 * 性别名称
	 */
	private String sexTypeName;

	/**
	 * @todo vo columns to String
	 */
	@Override
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public StaffInfoVO clone() {
		try {
			return (StaffInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * @return the beginDate
	 */
	public LocalDate getBeginDate() {
		return beginDate;
	}

	/**
	 * @param beginDate the beginDate to set
	 */
	public void setBeginDate(LocalDate beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * @return the endDate
	 */
	public LocalDate getEndDate() {
		return endDate;
	}

	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(LocalDate endDate) {
		this.endDate = endDate;
	}

	/**
	 * @return the organName
	 */
	public String getOrganName() {
		return organName;
	}

	/**
	 * @param organName the organName to set
	 */
	public void setOrganName(String organName) {
		this.organName = organName;
	}

	/**
	 * @return the sexTypeName
	 */
	public String getSexTypeName() {
		return sexTypeName;
	}

	/**
	 * @param sexTypeName the sexTypeName to set
	 */
	public void setSexTypeName(String sexTypeName) {
		this.sexTypeName = sexTypeName;
	}

}
