/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sagframe.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigDecimal;
import java.time.LocalDate;
import com.sagframe.sqltoy.showcase.vo.base.AbstractDeviceOrderInfoVO;

/**
 * @project sqltoy-oracle
 * @author zhongxuchen
 * @version 1.0.0
 * Table: SQLTOY_DEVICE_ORDER_INFO,Remark:硬件购销定单表(演示有规则单号) 	
 */
@SqlToyEntity
public class DeviceOrderInfoVO extends AbstractDeviceOrderInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3803808565657692676L;
	
	/** default constructor */
	public DeviceOrderInfoVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DeviceOrderInfoVO(String orderId)
	{
		this.orderId=orderId;
	}

	/** minimal constructor */
	public DeviceOrderInfoVO(String orderId,String deviceType,String psType,LocalDateTime transDate,String createBy,LocalDateTime createTime,String updateBy,LocalDateTime updateTime,Integer status)
	{
		this.orderId=orderId;
		this.deviceType=deviceType;
		this.psType=psType;
		this.transDate=transDate;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/** full constructor */
	public DeviceOrderInfoVO(String orderId,String deviceType,String psType,BigDecimal totalCnt,BigDecimal totalAmt,String buyer,String saler,LocalDateTime transDate,LocalDateTime deliveryTerm,String staffId,String organId,String createBy,LocalDateTime createTime,String updateBy,LocalDateTime updateTime,Integer status)
	{
		this.orderId=orderId;
		this.deviceType=deviceType;
		this.psType=psType;
		this.totalCnt=totalCnt;
		this.totalAmt=totalAmt;
		this.buyer=buyer;
		this.saler=saler;
		this.transDate=transDate;
		this.deliveryTerm=deliveryTerm;
		this.staffId=staffId;
		this.organId=organId;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public DeviceOrderInfoVO clone() {
		try {
			return (DeviceOrderInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
